=== Wilfred/ReVo-utilities/dtd/vokoxml.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--****************************************************
          KADRA STRUKTURO DE VORTARO
********************************************************-->

<!-- [vortaro] Radiko de la strukturarbo de vortaro. La elemento ampleksas
la tutan vortaron.<p>
Ĝi entenas aŭ prologon, precipan parton kaj epilogon aŭ plurajn
artikolojn. Prologo kaj epilogo estas nedevigaj. La ebleco de rekta
enteno de artikolo ne estas destinita por kompletaj vortaroj, sed por
eltiroj aŭ unuopa artikolo.-->

<!ELEMENT vortaro ((prologo?,precipa-parto,epilogo?)|art+)>
<!--ATTLIST vortaro
   xmlns CDATA #FIXED "http://steloj.de/voko"
-->

<!-- [prologo] Prologo de la vortaro. Ĝi povas enteni la titolo(j)n 
kaj aŭtoro(j)n de la vortaro kaj aliajn tekstojn.-->

<!ELEMENT prologo (#PCDATA|titolo|autoro|alineo)*>

<!-- [epilogo] Epilogo de la vortaro. Ĝia strukturo momente ne estas
specifita. Ĝi povas enhavi iun tekston.-->

<!ELEMENT epilogo (#PCDATA|alineo)*>

<!-- [titolo] Titolo de la vortaro. Ĝi estas entenata en la 
prologo. Pluraj titoloj estas permesitaj.-->

<!ELEMENT titolo (#PCDATA)>

<!-- [autoro] Indiko de aŭtoro(j) de la vortaro. 
Ĝi estas enhavata en la prologo kaj povas okazi tie plurfoje.-->

<!ELEMENT autoro (#PCDATA)>

<!-- [alineo] unuopa alineo en la prologo-teksto -->

<!ELEMENT alineo (#PCDATA|url)*>

<!-- [precipa-parto] Precipa parto de la vortaro. Ĝi enhavas rekte ĉiujn
artikolojn aŭ sekciojn aŭ partojn. 
Diversaj partoj povas dividi diversajn lingvojn de la kapvortoj.
Sekcioj grupigas vortojn komencighantajn je sama litero.
-->

<!ELEMENT precipa-parto (parto+|sekcio+|art+)>

<!-- [parto] Vortaroparto. Ĝi estas entenata en la precipa parto. Parto normale
prezentas unu lingvon en plurlingva vortaro aŭ lingvodirekton en
dulingva vortaro. Ĝia atributo <dfn>lng</dfn> indikas la lingvon de
la kapvortoj en la parto.-->

<!ELEMENT parto (sekcio+|art+)>
<!ATTLIST parto
	lng CDATA #IMPLIED
>

<!-- [sekcio] Sekcio en vortaro. Ĝi estas entenata en la precipa parto aŭ en
parto de ĝi kaj normale entenas ĉiujn artikolojn, kies kapvorto
komenciĝas je sama litero. La atributo <dfn>lit</dfn> indikas tiun
komencliteron.-->

<!ELEMENT sekcio (art+)>
<!ATTLIST sekcio
	lit CDATA #IMPLIED
>

<!-- ******************************************************
             STRUKTURO DE ARTIKOLO
***********************************************************-->

<!-- [%priskribaj-elementoj] La unuo <dfn>priskribaj-elementoj</dfn> 
listigas ĉiujn strukturilojn, kiuj priskribas kapvorton aŭ unuopan 
sencon de ĝi. Ĉar ili povas okazi multloke en la strukturo de 
artikolo estas avantaĝe difini tiun ĉi unuon.-->

<!-- priskribaj elementoj -->
<!ENTITY % priskribaj-elementoj 
  "fnt|gra|uzo|dif|ekz|rim|ref|refgrp|trd|trdgrp|bld|adm|url|mlg|lstref|tezrad">

<!-- [%tekst-stiloj] La unuo <dfn>tekst-stiloj</dfn> 
listigas ĉiujn strukturilojn, kiuj donas stilon al tekstoparto,
ekz. emfazita, citilita, altigita aŭ malaltigita teksto.
Aliaj elementoj klarigo kaj tildo kaj sencreferenco same povas esti
multloke, do ankaŭ ili estas listigitaj tie ĉi. -->

<!-- tekst-stiloj -->
<!ENTITY % tekst-stiloj "tld|sncref|klr|em|sup|sub|ctl|frm|nom|nac|esc">

<!-- [art] Unuopa artikolo de la vortaro. Ĝi povas okazi en
<dfn>vortaro</dfn> (se ne ekzistas precipa-parto),
<dfn>precipa-parto</dfn>, <dfn>parto</dfn> aŭ <dfn>sekcio</dfn>. Tio
dependas de la konkreta strukturo de la vortaro. Ĉiu artikolo
entenas unue kapvorton kaj poste aŭ priskribajn elementojn aŭ plurajn
derivaĵojn aŭ plurajn sencojn de la kapvorto aŭ subartikolojn. -->

<!ELEMENT art (kap,(subart|drv|snc|%priskribaj-elementoj;)*)>
<!ATTLIST art
	mrk CDATA #REQUIRED
>

<!-- [subart] Subartikolo. Ĝi povas okazi en <dfn>artikolo</dfn>,
se la signifoj de vorto (ofte ĉe prepozicioj kaj afiksoj) estas
tre diversaj. -->

<!ELEMENT subart (drv|snc|%priskribaj-elementoj;)*>
<!ATTLIST subart
	mrk ID #IMPLIED
>

<!-- [drv] Derivaĵo ene de artikolo. Unu artikolo povas priskribi plurajn
derivaĵojn de la kapvorto. Derivaĵo komenciĝas ja kapvorto kaj
priskribaj elementoj pri ĝi aŭ el unu aŭ pluraj sencoj aŭ el unu aŭ
pluraj subdividoj <dfn>subdrv</dfn>.-->

<!ELEMENT drv (kap,(subdrv|snc|%priskribaj-elementoj;)*)>
<!ATTLIST drv
	mrk ID #REQUIRED
>

<!-- [var] variaĵo de la vorto, ekz. meĥaniko - mekaniko, pomarbo -
pomujo. Ĝi povas enhavi fontindikon k.s., sed ankaŭ rimarkojn 
kaj ekzemplojn, sed ĝi ne havas propran difinon. Ĝi aperas ene
de kapvorto, ĉar ĝi ja estas ĝia variaĵo.
-->

<!ELEMENT var (kap,(uzo|klr|ekz|rim)*)>

<!-- [subdrv] Subderivaĵo. Ĝi grupigas plurajn proksimajn sencojn, se la
priskribita vorto havas tre multajn sencojn. Tio povas
rezulti en pli klara strukturo de la artikolo. La subdividaĵoj
estas nombrataj per A), B), ... -->

<!ELEMENT subdrv (snc|%priskribaj-elementoj;)*>
<!ATTLIST subdrv
	mrk ID #IMPLIED
>

<!-- [snc] Senco de unuopa vorto en artikolo. Komparu la latinajn ciferojn en
la artikoloj de PIV. Per mrk oni povas referenci sencon de alie. Per ref oni
referencas al alia senco samartikola (uzata en malmultaj longaj artikoloj, ekz.
"al". Per num la senco ricevas numeron. Atentu, ke future simbolaj nomoj por
la sencoj estos perferataj kaj do numerado okazas automate ignorante la atributon
num. -->

<!ELEMENT snc (subsnc|%priskribaj-elementoj;)*>
<!ATTLIST snc
	mrk ID #IMPLIED
        num CDATA #IMPLIED
	ref CDATA #IMPLIED
>

<!-- [subsnc] Subsenco ene de senco. Ĝi redonas subtilaĵojn ene de unu senco.
Ili estas nombrataj per a), b), ... -->

<!ELEMENT subsnc (%priskribaj-elementoj;)*>
<!ATTLIST subsnc
	mrk ID #IMPLIED
        ref CDATA #IMPLIED
>

<!-- [sncref] Referenco al alia senco. Tiu elemento estas anstatauigata
 per la numero de la referencita senco. Vi povas forlasi la atributon 
 ref, se ekzistas parenca elemento ref, kies atributo cel montras al la
 referencita senco.
-->

<!ELEMENT sncref EMPTY>
<!ATTLIST sncref
       ref CDATA #IMPLIED
>

<!-- ************************************************
            STRUKTUROJ DE DETALAJ ELEMENTOJ
*****************************************************-->

<!-- [kap] kapvorto okazas en du kuntekstoj - komence de artikolo
kaj komence de derivaĵo, en la unua kazo ĝi signas radikon
en la dua kazo ĝi konsistas el iuj literoj kaj eble tildo
refencanta al la kapvorto, krome en la kapvorto povas okazi
fontindiko.
-->

<!ELEMENT kap (#PCDATA|rad|ofc|fnt|tld|var)*>

<!-- [rad] Radiko de kapvorto. Ĝi estas bezonata por anstaŭigo
de tildoj. Sekve la "radiko" de afiksoj kaj finaĵoj estu
ili mem, sen la streketoj antaŭe aŭ malantaŭe.-->

<!ELEMENT rad (#PCDATA)>

<!-- [ofc] Oficialeco de la kapvorto/derivajho, 
  povas esti *, 1, ..., 8 kiel en PIV -->

<!ELEMENT ofc (#PCDATA)>

<!-- [fnt] Fonto enhavas informojn pri autoro, verko, trovloko
au aliajn informojn.-->

<!ELEMENT fnt (#PCDATA|bib|aut|vrk|lok|url)*>

<!-- [gra] kiel grammatikaj informoj momente estas permesataj
nur indiko de la vortspeco.-->

<!ELEMENT gra (#PCDATA|vspec)*>

<!-- [vspec] Vortspeco. Ekz. subst. por substantivo; tr./ntr.
por transitivaj kaj netransitivaj verboj ktp.-->

<!ELEMENT vspec (#PCDATA)>

<!-- [uzo] La uzo povas esti stilo, fako, regiono aŭ alia klarigo,
kiel estas uzata la vorto au termino. Por la fakoj kaj stiloj uzu
unu el la aliloke listigitaj mallongigoj.
-->

<!ELEMENT uzo (#PCDATA|tld)*>
<!ATTLIST uzo
	tip (fak|reg|klr|stl) #IMPLIED
>

<!-- [dif] Difino estas la frazo difinanta la vorton, sencon aŭ
subsencon. Ĝi povas esti ankaŭ en alia(j) lingvo(j) ol la vorto
mem. La lingvon indikas la atributo <dfn>lng</dfn>.
-->

<!ELEMENT dif (#PCDATA|trd|trdgrp|ref|refgrp|ekz|snc|%tekst-stiloj;)*>
<!ATTLIST dif
	lng CDATA #IMPLIED
>

<!-- [ekz] Ekzemplo konsistas el ekzemplofrazo,
klarigoj kaj fonto.
-->

<!ELEMENT ekz (#PCDATA|fnt|uzo|ref|refgrp|ind|trd|trdgrp|%tekst-stiloj;)*>
<!ATTLIST ekz
	mrk ID #IMPLIED
>

<!-- [rim] Rimarko povas enhavi iujn indikojn pri la vorto aŭ
senco, krome referencojn, ekzemplojn, emfazitajn partojn.
-->
<!ELEMENT rim (#PCDATA|ref|refgrp|ekz|aut|fnt|%tekst-stiloj;)*>
<!ATTLIST rim
        num CDATA #IMPLIED
	mrk ID #IMPLIED
> 

<!-- [refgrp] Referencgrupo grupigas plurajn samtipajn
referencojn. La tipon indikas la atributo <dfn>tip</dfn>.
Tiukaze ne uzu la atributon <dfn>tip</dfn> en la subelementoj
<dfn>ref</dfn>!
-->

<!ELEMENT refgrp (#PCDATA|ref)*>
<!ATTLIST refgrp
	tip (vid|hom|dif|sin|ant|super|sub|prt|malprt|lst|ekz) "vid"
>

<!-- [ref] Referenco montras al alia, simil- aŭ alisignifa vorto,
oni povas distingi diversajn rilattipon al la
referencita vorto. La enhavo de la referenco estas tio, kio
aperas en la legebla teksto. La referencitan vorton mem
oni difinas per la atributo "cel". La celon oni plej
bone difinas per: radiko.derivaĵo.difino, oni povas uzi
la numeron de la difino au derivaĵo. Plej bone oni
generas la markojn (t.e. la eblaj celoj de referenco)
aŭtomate por minimumigi erarojn.
La atributoj "lst" kaj "val" servas por referenci al vortlisto (tip="lst"),
ekz. monatoj. Se temas pri ordigita listo, vi povas indiki valoron per "val",
ekz. "3" che la monato marto.
-->

<!ELEMENT ref (#PCDATA|tld|klr|sncref)*>
<!ATTLIST ref
	tip (vid|hom|dif|sin|ant|super|sub|prt|malprt|lst|ekz) #IMPLIED
	cel CDATA #REQUIRED
        lst CDATA #IMPLIED
	val CDATA #IMPLIED
>

<!-- [tez] NE PLU UZU! Tezaŭra nodo. Ĝi permesas referenci al tio, same kiel
 al kap kaj mem povas referenci al alia nodo.
<!ELEMENT tez (#PCDATA|tld|klr|ref|refgrp)*>
<!ATTLIST tez
        mrk CDATA #REQUIRED
        tip (super|malprt|listo) #IMPLIED
	cel CDATA #REQUIRED
>
-->

<!-- [lstref] Referenco al vortlisto el artikolo.
-->
<!ELEMENT lstref (#PCDATA|tld|klr)*>
<!ATTLIST lstref
        lst CDATA #REQUIRED
>

<!-- [tezrad] Tezaŭraradiko. La kapvorto aperas en la enir-listo
de la tezaŭro. Se vi uzas la atributon fak, ĝi aperas en la 
struktura enirlisto de la fako -->
<!ELEMENT tezrad EMPTY>
<!ATTLIST tezrad
        fak CDATA #IMPLIED
>

<!-- [trdgrp] Tradukgrupo kunigas diversajn tradukojn de
sama lingvo.
-->
<!ELEMENT trdgrp (#PCDATA|trd)*>
<!ATTLIST trdgrp
	lng CDATA #REQUIRED
>

<!-- [trd] Traduko kosistas el traduka vorto aŭ frazo
kaj klarigoj, poste povos sekvi aliaj elementoj.
-->
<!ELEMENT trd (#PCDATA|klr|ind|mll|ofc)*>
<!ATTLIST trd
	lng CDATA #IMPLIED
        fnt CDATA #IMPLIED
>

<!-- [ind] Parto de traduko, kiu liveras la kapvorton en la
indekso, do &lt;trd&gt;sich &lt;ind&gt;bem&uuml;hen&lt;/ind&gt;&lt;/trd&gt;
aperas sub bem&uuml;hen. Aŭ parto de ekzemplo aŭ bildpriskribo, al
kiu rilatas internaj tradukoj ktp.
-->
<!ELEMENT ind (#PCDATA|tld|klr|mll)*>

<!ELEMENT mll (#PCDATA|tld|klr|ind)*>
<!ATTLIST mll
        tip (kom|mez|fin) #IMPLIED
>

<!-- [bld] Bildo povas ilustri iun vorton aŭ sencon. Per la
atributo <dfn>lok</dfn> ĝi
referencas al ekstera dosiero, kiu entenas la bildon.
Per <dfn>alt</dfn> kaj <dfn>lrg</dfn> vi povas doni fiksan formaton.
Per <dfn>tip</dfn> vi donas tipon de la bildo, t.e. <dfn>img</dfn>
por JPEG, GIF, PNG-bildo, <dfn>svg</dfn> por SVG-vektorgrafiko.
Per <dfn>aut</dfn> vi donas aŭtoron kaj <dfn>prm</dfn> la permesilon
laŭ kiu la bildo rajtas esti uzata (vd ĉe Wikimedia Commons).
-->
<!ELEMENT bld (#PCDATA|tld|klr|fnt|ind|trd|trdgrp)*>
<!ATTLIST bld
	lok CDATA #REQUIRED
	mrk ID #IMPLIED
	tip (img|svg) "img"
	alt CDATA #IMPLIED 
	lrg CDATA #IMPLIED
        prm CDATA #IMPLIED
>

<!-- [adm] Administraj informoj estu por redaktado. Ili povus
enhavi informojn pri kreodato, ŝanĝdato, aŭtoro, eraroj kaj
plibonigproponoj pri artikolo. Ĝia strukturo ankoraŭ estas
diskutatebla.
-->
<!ELEMENT adm (#PCDATA|aut)*>

<!-- [tld] Tildo rilatas al la radiko, donita en la kapvorto
ĝi ne bezonas enhavon. La atributo <dfn>lit</dfn> indikas alian
komencliteron ol havas la radiko. Grava por majuskligo kaj
minuskligo.
-->
<!ELEMENT tld EMPTY>
<!ATTLIST tld
            lit CDATA #IMPLIED>       

<!-- [klr] Klarigo pri vorto, difino, ekzemplo ktp.-->
<!ELEMENT klr (#PCDATA|trd|trdgrp|ekz|ref|refgrp|%tekst-stiloj;)*>
<!ATTLIST klr
            tip (ind|amb) #IMPLIED>

<!-- [bib] Bibliografia indiko por fonto, estas mallongigo el
listo de difinitaj bibliografieroj kaj anstataŭas verko- kaj aŭtoroindikon
en la fontoj.
-->
<!ELEMENT bib (#PCDATA)*>

<!-- [vrk] Verko, en kiu troviĝas citita frazo aŭ vorto -->
<!ELEMENT vrk (#PCDATA|url)*>

<!-- [lok] Loko, kie troviĝas citita frazo aŭ vorto en verko -->
<!ELEMENT lok (#PCDATA|url)*>

<!-- [aut] Aŭtoro de citita frazo aŭ verko -->
<!ELEMENT aut (#PCDATA)>

<!-- [frm] Matematika au kemia formulo, por matematikaj formuloj oni povas
    ankaŭ doni esprion laŭ sintakso de AsciiMath por pli bela kompostado -->
<!ELEMENT frm (#PCDATA|sup|sub|g|k)*>
<!ATTLIST frm 
          kod (am) #IMPLIED
          am CDATA #IMPLIED>

<!-- [g] Grasa parto de formulo, ekz. vektoro, matrico k.s.,
  bv. uzi nur en frm -->
<!ELEMENT g (#PCDATA)*>

<!-- [k] Kursiva parto de formulo, ekz. variablo k.s.,
  bv. uzi nur en frm -->
<!ELEMENT k (#PCDATA)*>

<!-- [em] Emfazo. Normale grase skribata vortoj.-->
<!ELEMENT em (#PCDATA|tld)*>

<!-- [sup] altigita teksto, ekz. en ĥemiaj formuloj -->
<!ELEMENT sup (#PCDATA|g|k)*>

<!-- [sub] malaltigita teksto, ekz. en ĥemiaj formuloj -->
<!ELEMENT sub (#PCDATA|g|k)*>

<!-- [ctl] citilita teksto, ekz. memindika uzo de vorto -->
<!ELEMENT ctl (#PCDATA|tld|em|frm)*>

<!-- [url] Referenco al iu ekstera dosiero. En la HTML-versio de vortaro
tio fariĝas &lt;a href=...&gt; Anstataŭ la TTT-ejo prefere uzu
la alinomojn difinitajn en la DTD, ĉar alikaze la referencoj tro
ofte malvalidiĝus. -->

<!ELEMENT url (#PCDATA)>
<!ATTLIST url 
          ref CDATA #IMPLIED>

<!-- [mlg] mallongigo de la kapvorto, ekz. che nomoj de organizajhoj. 
Per "kod" vi povas indiki devenon de la mallongigo, ekz. ISO-3166 ĉe landokodoj -->

<!ELEMENT mlg (#PCDATA)>
<!ATTLIST mlg
          kod CDATA #IMPLIED>

<!-- [nom] nomo ne esperantigita, tiuj estas ignorataj dum vortkontrolo  -->
<!ELEMENT nom (#PCDATA)>

<!-- [nac] nacilingva vorto aŭ esprimo, tiuj estas ignorataj dum vortkontrolo  -->
<!ELEMENT nac (#PCDATA)>

<!-- [esc] escepte formita (laŭ vidpunkto de vortanalizila gramatiko) 
esperanta vorto aŭ esprimo, tiuj estas ignorataj dum vortkontrolo  -->
<!ELEMENT esc (#PCDATA)>


<!-- *************************************************
                   LITEROJ
******************************************************
-->

<!ENTITY % signoj SYSTEM "../dtd/vokosgn.dtd">
%signoj;

<!-- ************************************************
                   MALLONGIGOJ
*****************************************************
-->

<!ENTITY % mallongigoj SYSTEM "../dtd/vokomll.dtd">
%mallongigoj;

<!-- *************************************************
                   URLoj
******************************************************
-->

<!ENTITY % urloj SYSTEM "../dtd/vokourl.dtd">
%urloj;

=== Wilfred/ReVo-utilities/xml/entomolog.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: entomolog.xml,v 1.2 2010/04/27 16:30:57 revo Exp $">
<kap>
  <ofc>7</ofc>
  <rad>entomolog</rad>/o <fnt><bib>PIV2</bib></fnt>
</kap>
<drv mrk="entomolog.0o">
  <kap><tld/>o</kap>
  <snc>
    <ref tip="dif" cel="entomo.0isto">entomologiisto</ref>
  </snc>
  <trd lng="en">entomologist</trd>
  <trd lng="pl">entomolog</trd>
</drv>
</art>

<!--
$Log: entomolog.xml,v $
Revision 1.2  2010/04/27 16:30:57  revo
Sebastian Cyprych: +trd pl

Revision 1.1  2010/04/24 17:07:15  revo
Russ Williams: nova artikolo

-->
</vortaro>

=== Wilfred/ReVo-utilities/xml/muzikolog.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: muzikolog.xml,v 1.3 2009/08/13 16:30:38 revo Exp $">
<kap>
  <rad>muzikolog</rad>/o
</kap>
<drv mrk="muzikolog.0o">
  <kap><tld/>o</kap>
  <snc mrk="muzikolog.0o.MUZ">
    <uzo tip="fak">MUZ</uzo>
    <ref tip="dif" cel="muzik.0osciencisto.MUZ">muzikosciencisto</ref>
    <ekz>
      la <tld/>oj ne havas grandajn malfacila&jcirc;ojn komparante
      melodiojn, kiujn &ccirc;iam oni skribas per la sama skribsistemo
      <fnt>
      <aut>F. Hoerburger</aut>,
      <vrk><url
      ref="http://donh.best.vwh.net/Esperanto/Literaturo/Revuoj/np/np5802/kinetografio.html">
      Kinetografio kaj dancesploro</url></vrk>,
      <lok>Norda Prismo 1958:02, p. 81-83a</lok>
      </fnt>.
    </ekz>
  </snc>
  <trd lng="bg">&c_m;&c_u;&c_z;&c_i;&c_k;&c_o;&c_l;&c_o;&c_g;</trd>
  <trd lng="fr">musicologue</trd>
  <trd lng="it">musicologo</trd>
  <trd lng="nl">musicoloog</trd>
</drv>
</art>

<!--
$Log: muzikolog.xml,v $
Revision 1.3  2009/08/13 16:30:38  revo
Wieland Pusch: +trd bg

Revision 1.2  2009/08/11 16:31:30  revo
Paul Peeraerts: +trd nl

Revision 1.1  2007/03/24 17:30:32  revo
Jeromo Vasxe: nova artikolo

-->
</vortaro>

=== Wilfred/ReVo-utilities/xml/kartunkin.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: kartunkin.xml,v 1.1 2008/08/29 16:30:28 revo Exp $">
<kap>
<rad>kartunkin</rad>/o
</kap>
<drv mrk="kartunkin.0o">
  <kap><tld/>o</kap>
  <snc>
  <uzo tip="fak">KIN</uzo>
    <dif>
<ref tip="vid" cel="kin.0o.KIN.arto">Kino</ref> pere de desegna&jcirc;oj.
    </dif>
  </snc>
<trd lng="it">cinema d'animazione</trd>
</drv>
</art>

<!--
$Log: kartunkin.xml,v $
Revision 1.1  2008/08/29 16:30:28  revo
Antonio Codazzi: nova artikolo

-->
</vortaro>

=== Wilfred/ReVo-utilities/xml/artrit1.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: artrit1.xml,v 1.3 1999/10/06 08:58:16 revo Exp $">
<kap>
<rad>artritism</rad>/o
</kap>
<drv mrk="artrit1.0o">
<kap><tld/>o</kap>
<uzo tip="fak">MED</uzo>
<snc>
<dif>
artritema temperamento.  
</dif>
</snc>
</drv>
</art></vortaro>

=== Wilfred/ReVo-utilities/xml/principe.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: principe.xml,v 1.3 2009/10/28 17:30:44 revo Exp $">
<kap>
  <rad>principe</rad>/o
</kap>

<drv mrk="principe.0o">
  <kap>
    <tld lit="P"/>o
    <fnt>
      <vrk>Oficiala Informo de AdE</vrk>,
      <lok>numero 12</lok>
    </fnt>
  </kap>
  <snc mrk="principe.0o.GEOG">
    <uzo tip="fak">GEOG</uzo>
    <dif>
      <ref tip="vid" cel="atlant.0o.GEOG">Atlantika</ref> 
      (Gvinea Golfo) insulo, konsitiganta kun <ref tip="vid" 
      cel="santome.0o.GEOG">Santomeo</ref>
      &scirc;taton <ref tip="malprt"
      cel="santome.0oprincipeo.sxtato">Santomeo kaj Principeo</ref>.
      Situo: 1&ring;37&#8242;N 7&ring;24&#8242;E.
    </dif>
    <trd lng="bg">&c_P;&c_r;&c_i;&c_n;&c_s;&c_i;&c_p;&c_i;</trd>
    <trd lng="de">Pr&iacute;ncipe</trd>
    <trd lng="en">Pr&iacute;ncipe</trd>
    <trd lng="nl">Principe</trd>
    <trdgrp lng="pl">
      <trd>Wyspa Ksi&aogonek;&zdot;eca</trd>
    </trdgrp>
  </snc>
</drv>

</art>

<!--
$Log: principe.xml,v $
Revision 1.3  2009/10/28 17:30:44  revo
Paul Peeraerts: +nl

Revision 1.2  2009/05/19 17:00:33  revo
Wieland Pusch: +trd bg,de

Revision 1.1  2009/05/18 16:30:36  revo
Sebastian Cyprych: nova artikolo

-->
</vortaro>

=== Wilfred/ReVo-utilities/xml/gratif1.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: gratif1.xml,v 1.5 2001/10/15 18:17:39 revo Exp $">
<kap>
<rad>gratifikaci</rad>/o
<fnt>Z</fnt>
</kap>
<drv mrk="gratif1.0o">
<kap><tld/>o</kap>
<uzo tip="fak">EKON</uzo>
<uzo tip="stl">ARK</uzo>
<fnt><bib>PV</bib></fnt>
<snc>
<ref tip="dif" cel="gratif.0o">gratif(ik)o.</ref>
</snc>
</drv>
</art>
<!--
$Log: gratif1.xml,v $
Revision 1.5  2001/10/15 18:17:39  revo
Marc Bavant: sxovis ref ekster dif, kor ref cel, +uzo ARK, +fnt

Revision 1.4  2001/05/29 18:14:31  revo
Ulrich Fellmann: + uzo EKON

-->
</vortaro>

=== Wilfred/ReVo-utilities/xml/vaux.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: vaux.xml,v 1.2 2009/09/26 16:32:25 revo Exp $">
<kap>
<rad>va&ubreve;</rad>
</kap>
<drv mrk="vaux.0">
  <kap><tld/></kap>
  <gra><vspec>sonimito</vspec></gra>
  <snc>
    <dif>
      Sono de hunda bleko. <ekz><tld/>-<tld/></ekz>
    </dif>
  </snc>
  <trd lng="hu">vau</trd>
</drv>
</art>

<!--
$Log: vaux.xml,v $
Revision 1.2  2009/09/26 16:32:25  revo
Jozefo Horvath: + trd hu

Revision 1.1  2008/08/25 18:15:41  revo
Antonio Codazzi: nova artikolo

-->
</vortaro>

=== Wilfred/ReVo-utilities/xml/ekzokrin.xml
<?xml version="1.0"?>
<!DOCTYPE vortaro SYSTEM "../dtd/vokoxml.dtd">

<vortaro>
<art mrk="$Id: ekzokrin.xml,v 1.2 2007/06/27 16:31:03 revo Exp $">
<kap>
  <rad>ekzokrin</rad>/a <fnt><bib>NePiv</bib></fnt>
</kap>
<drv mrk="ekzokrin.0a">
  <kap><tld/>a</kap>
  <uzo tip="stl">RAR</uzo>
  <snc mrk="ekzokrin.0a.FIZL">
    <uzo tip="fak">FIZL</uzo>
      <ref tip="dif" cel="dukt.0a.FIZL">dukta</ref>
      <ekz>
        biologie, haroj kaj similaj fenomenoj estas nur sekrecioj de 
        <tld/>aj glandoj, fari&gcirc;intaj sufi&ccirc;e solidaj, por resti a&ubreve; kiel 
        flekseblaj haroj, a&ubreve; kiel pli solida skvamo, &scirc;elo, ungo, hufo
        <fnt>
          <aut>E. Pauli</aut>,
          <vrk><url ref="http://www.cfh.ufsc.br/~simpozio/">Enciklopedio 
          simpozio</url></vrk>,
          <lok>artikolo &leftquot;haro&rightquot;, 1996-05</lok>
        </fnt>.
      </ekz>
  </snc>
  <trd lng="pt">ex&#243;crino</trd>
</drv>
</art>

<!--
$Log: ekzokrin.xml,v $
Revision 1.2  2007/06/27 16:31:03  revo
Tulio Flores: +tr pt

Revision 1.1  2006/12/21 17:30:25  revo
Jeromo Vasxe: nova artikolo

-->
</vortaro>
